version: '3'

services:

  postgres:

    image: postgres:15

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5433:5432"

  airflow-webserver:

    image: apache/airflow:2.10.0

    depends_on:
      - postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    volumes:
      - ./dags:/opt/airflow/dags

    ports:
      - "8080:8080"

    command: webserver

  airflow-scheduler:

    image: apache/airflow:2.10.0

    depends_on:
      - postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    volumes:
      - ./dags:/opt/airflow/dags

    command: scheduler